export const posts = [
  {
    id: 1,
    title: "Post 1",
    img: "https://via.placeholder.com/600/92c952",
    thumbnailUrl: "https://via.placeholder.com/150/92c952",
    desc: "Description for Post 1",
    longDesc: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer lacinia lectus eget justo accumsan ullamcorper. Sed volutpat urna non lacus gravida aliquet. Phasellus congue ligula vitae tellus ultrices, sed dapibus felis consectetur. Proin quis erat interdum, aliquam massa a, iaculis tellus. Maecenas non elit ac dui sagittis consequat. Fusce semper metus elit, at congue diam finibus ut. Sed tristique aliquam eros, sed interdum nulla volutpat vel. Phasellus ac pharetra libero. Vivamus malesuada tellus sit amet dui bibendum, id faucibus risus lacinia. Pellentesque tristique hendrerit pulvinar. Morbi id rutrum ipsum. Quisque et tincidunt nulla. Nunc placerat rutrum mauris id maximus. Duis scelerisque malesuada risus a efficitur.",
  },
  {
    id: 2,
    title: "Post 2",
    img: "https://via.placeholder.com/600/ff0000",
    thumbnailUrl: "https://via.placeholder.com/150/ff0000",
    desc: "Description for Post 2",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  // Add more posts here...
  {
    id: 3,
    title: "Post 15",
    img: "https://via.placeholder.com/600/0000ff",
    thumbnailUrl: "https://via.placeholder.com/150/0000ff",
    desc: "Description for Post 15",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 4,
    title: "Post 16",
    img: "https://via.placeholder.com/600/00ff00",
    thumbnailUrl: "https://via.placeholder.com/150/00ff00",
    desc: "Description for Post 16",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 5,
    title: "Post 17",
    img: "https://via.placeholder.com/600/ff00ff",
    thumbnailUrl: "https://via.placeholder.com/150/ff00ff",
    desc: "Description for Post 17",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  // Add more posts here...
  {
    id: 6,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 7,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 8,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 9,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 10,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 11,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 12,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },

  {
    id: 13,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 14,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },
  {
    id: 15,
    title: "Post 30",
    img: "https://via.placeholder.com/600/ffff00",
    thumbnailUrl: "https://via.placeholder.com/150/ffff00",
    desc: "Description for Post 30",
    longDesc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempus lorem ac est vestibulum, vitae fermentum nisl interdum. Nullam sit amet elit a dui auctor efficitur. Integer consequat turpis ac lorem tempus, vitae efficitur erat sollicitudin. Vivamus dictum neque a mi facilisis, vitae cursus lectus fermentum. Nunc pellentesque mauris nec mauris sollicitudin, ac condimentum ante interdum. Integer non bibendum turpis. In efficitur, nulla in facilisis tincidunt, est elit dapibus orci, a facilisis leo tellus ac nisi. Maecenas commodo nisi a sem tincidunt, nec pharetra elit commodo. Curabitur sit amet mauris lectus. Nam gravida rhoncus dui at malesuada. In vitae vulputate libero, eget aliquam nulla. Phasellus varius faucibus risus, non pharetra turpis. Suspendisse efficitur elit enim, ut mattis elit semper at. Curabitur a odio sed risus consectetur viverra. Nam pharetra ante tortor, vel fringilla urna vulputate in.",
  },


];
